diodeinc/pcb

- README.md
Following the README as-is results in the following error
`Error: Failed to resolve module path '@github/diodeinc/stdlib:main/generics/LED.star': File not found`
and requires renaming reference to LED.star -> Led.star and variable names renamed accordingly for consistency.
> fix(README): Rename LED -> Led for Quick Start section

- Cargo.lock
- crates/pcb-buildifier/build.rs
- crates/pcb-buildifier/src/lib.rs
- flake.lock
- flake.nix
```
nix profile install github:diodeinc/pcb
```
or to test
```
nix run github:0xcaff/pcb/martin/nix -- --help
```
kicad isn't packaged here yet but can deal with that later
used crane as there is a bug in nixpkgs rust https://discourse.nixos.org/t/rust-with-git-deps-symbolic-link-error-to-cargo-vendor-dep/28841 and naserk had some issue as well. crane isn't ideal because it doesn't cache properly but now it one click installs so whatever. i will go make the rust builds less stupid in nix with dynamic derivations soon and come back and fix this then
> add nix flake

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- crates/pcb-layout/tests/layout_generation.rs
- crates/pcb-zen-core/src/lib.rs
- crates/pcb-zen-core/src/load_spec.rs
- crates/pcb-zen-core/tests/common/mod.rs
- crates/pcb-zen-core/tests/core_load_resolver.rs
- crates/pcb-zen-wasm/src/lib.rs
- crates/pcb-zen/src/bundle.rs
- crates/pcb-zen/src/lib.rs
- crates/pcb-zen/src/load.rs
- crates/pcb-zen/src/lsp/mod.rs
- crates/pcb-zen/tests/common/mod.rs
- crates/pcb/Cargo.toml
- crates/pcb/src/bom.rs
- crates/pcb/src/build.rs
- crates/pcb/src/clean.rs
- crates/pcb/src/layout.rs
- crates/pcb/src/main.rs
- crates/pcb/src/open.rs
- crates/pcb/src/release.rs
- crates/pcb/src/tracking_resolver.rs
- crates/pcb/src/upgrade/codemods/remove_directory_loads.rs
- crates/pcb/src/vendor.rs
- crates/pcb/src/workspace.rs
Build from within a release dir to confirm `pcb build --offline` works:
```
> cargo run --release -- release test-workspaces/with-pcb-toml/boards/WorkspaceTestBoard.zen
Compiling pcb v0.2.0-prerelease.2 (/Users/akhilles/src/diode/pcb/crates/pcb)
Finished `release` profile [optimized] target(s) in 2.68s
Running `target/release/pcb release test-workspaces/with-pcb-toml/boards/WorkspaceTestBoard.zen`
✓ Release information gathered
Release Metadata
{
"git": {
"describe": "ac7c446",
"workspace": "/Users/akhilles/src/diode/pcb/test-workspaces/with-pcb-toml"
},
"release": {
"created_at": "2025-08-15T17:08:37.373435+00:00",
"layout_path": "/Users/akhilles/src/diode/pcb/test-workspaces/with-pcb-toml/boards/build/WorkspaceTestBoard",
"staging_directory": …
```
> [DIO-301] Add `pcb vendor`, `pcb build --offline`

- crates/pcb-test-utils/src/sandbox.rs
- crates/pcb-zen-core/src/lib.rs
- crates/pcb/src/release.rs
- crates/pcb/src/vendor.rs
- crates/pcb/src/workspace.rs
- crates/pcb/tests/release.rs
- crates/pcb/tests/simple.rs
- crates/pcb/tests/snapshots/release__case_insensitive_tag_build.snap
- crates/pcb/tests/snapshots/release__release_basic_build.snap
- crates/pcb/tests/snapshots/release__release_full_build.snap
- crates/pcb/tests/snapshots/release__release_with_file.snap
- crates/pcb/tests/snapshots/release__release_with_file_build.snap
- crates/pcb/tests/snapshots/release__release_with_git_build.snap
- crates/pcb/tests/snapshots/simple__simple_workspace_release.snap
Remove the filtering that I added, it's not needed. This can be further
simplified in the future by merging tracked_local_files into
path_to_spec.
Also, build after release in snapshot tests.
> Copy all tracked files to release src

- crates/pcb-test-utils/src/sandbox.rs
- crates/pcb-zen/src/git.rs
- crates/pcb-zen/src/load.rs
- crates/pcb/src/vendor.rs
- crates/pcb/tests/build.rs
- crates/pcb/tests/snapshots/build__commit_stable_ref.snap
Previously, we would do a shallow clone of the default branch and then attempt to checkout the commit. This doesn't work if the commit is not on the default branch.
Also, allow specifying short hash (len 7).
> Fix fetching a commit from a non-default branch

- crates/pcb-layout/src/lib.rs
- crates/pcb-zen-core/src/convert.rs
Since `Path()` resolves to an absolute path, we shouldn't prefix it with module path.
I tested this with non-vendored and vendored workspaces
> Fix layout sync when using `Path()`

- crates/pcb-zen-core/src/lib.rs
We use `InMemoryFileProvider` in WASM to mock out a file system where we don't really have one, and as part of this we re-implement path canonicalization. It turns out "/some/path" in wasm is not counted as "absolute" according to `std::fs`, which causes this assert to wrongfully trigger when running in WASM.
> Temporarily disable assert

- crates/pcb/src/release.rs
The `layout_path` would resolve to the folder that contains the layout (not the file), so we don't need to look at the parent directory. This causes a problem if you have sub-layouts nested within the board directory, since it will end up copying those sub-layouts instead of the main layout.
> Use correct layout path when copying layout files

- crates/pcb-zen-core/src/lang/interface.rs
- crates/pcb-zen-core/tests/snapshots/input__config_types.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_comprehensive_net_promotion.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_promotion_deserialization.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_using_deep_recursion.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_using_deserialization_roundtrip.snap
- crates/pcb-zen/tests/snapshots/input__correct_usage_with_explicit_net_access.snap
Remove spurious net name deduplication.
```
Level1 = interface(
net = Net("INNER"),
)
Level2 = interface(
level1 = Level1(),
)
Level3 = interface(
level2 = Level2(),
)
l1 = Level1()
print(l1.net.name)
l2 = Level2()
print(l2.level1.net.name)
l3 = Level3()
print(l3.level2.level1.net.name)
l1_named = Level1("L1")
print(l1_named.net.name)
l2_named = Level2("L2")
print(l2_named.level1.net.name)
l3_named = Level3("L3")
print(l3_named.level2.level1.net.name)
```
before:
```
INNER_3
INNER_4
INNER
L1_INNER
L2_LEVEL1_INNER
INNER
```
after:
```
INNER
LEVEL1_INNER
LEVEL2_LEVEL1_INNER
L1_INNER
L2_LEVEL1_INNER
L3_LEVEL2_LEVEL1_INNER
```
> Fix hierarchical net naming

- crates/pcb-zen-core/src/lang/interface.rs
- crates/pcb-zen-core/src/lang/net.rs
- crates/pcb-zen-core/tests/interface.rs
- crates/pcb-zen-core/tests/net.rs
- crates/pcb-zen-core/tests/snapshots/input__interface_net_template_basic.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_comprehensive_net_promotion.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_invoke_with_net_override.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_multiple_instances_independent_symbols.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_nested_symbol_copy.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_post_init_callback.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_promotion_deserialization.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_serialization_formats.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_single_net_naming.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_transitive_promotion.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_using_deep_recursion.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_using_deserialization_roundtrip.snap
- crates/pcb-zen-core/tests/snapshots/net__interface_net_template_naming.snap
- crates/pcb-zen/tests/interface_templates.rs
- crates/pcb-zen/tests/snapshots/input__correct_usage_with_explicit_net_access.snap
- crates/pcb-zen/tests/snapshots/interface_templates_snapshot__interface_net_template_basic.snap
- crates/pcb-zen/tests/snapshots/spice_model__snapshot_sim_divider.snap
Mainly affects power, gnd net naming.
```
Level1 = interface(
net = Net("INNER"),
)
Level2 = interface(
level1 = Level1(),
)
Level3 = interface(
level2 = Level2(),
)
l1 = Level1()
print(l1.net.name)
l2 = Level2()
print(l2.level1.net.name)
l3 = Level3()
print(l3.level2.level1.net.name)
l1_named = Level1("L1")
print(l1_named.net.name)
l2_named = Level2("L2")
print(l2_named.level1.net.name)
l3_named = Level3("L3")
print(l3_named.level2.level1.net.name)
```
before:
```
INNER
LEVEL1_INNER
LEVEL2_LEVEL1_INNER
L1_INNER
L2_LEVEL1_INNER
L3_LEVEL2_LEVEL1_INNER
```
after:
```
_INNER
LEVEL1
LEVEL2_LEVEL1
L1
L2_LEVEL1
L3_LEVEL2_LEVEL1
```
> Don't suffix inner net name for single-net instances

- .github/workflows/test.yml
- crates/pcb-zen-core/src/config.rs
- crates/pcb-zen/src/load.rs
- crates/pcb/src/release.rs
- crates/pcb/src/tag.rs
- crates/pcb/tests/path.rs
- crates/pcb/tests/release.rs
- crates/pcb/tests/simple.rs
- crates/pcb/tests/snapshots/path__path_local_mixed_release.snap
- crates/pcb/tests/snapshots/release__case_insensitive_tag.snap
- crates/pcb/tests/snapshots/release__case_insensitive_tag_build.snap
- crates/pcb/tests/snapshots/release__release_basic.snap
- crates/pcb/tests/snapshots/release__release_basic_build.snap
- crates/pcb/tests/snapshots/release__release_full.snap
- crates/pcb/tests/snapshots/release__release_full_build.snap
- crates/pcb/tests/snapshots/release__release_with_file.snap
- crates/pcb/tests/snapshots/release__release_with_file_build.snap
- crates/pcb/tests/snapshots/release__release_with_git.snap
- crates/pcb/tests/snapshots/release__release_with_git_build.snap
- crates/pcb/tests/snapshots/simple__simple_workspace_release.snap
Before:
```
pcb tag --board <BOARD> --version <VERSION> [PATH]
pcb release <zen_path>  # inconsistent - used file path
```
After:
```
pcb tag --board <BOARD> --version <VERSION> [PATH]
pcb release --board <BOARD> [PATH]  # now consistent
```
Also, prefix the board name so that the folders + zip file names are easier to grok.
Before:
- Staging: .pcb/releases/MyBoard/v1.0.0/
- Zip: .pcb/releases/MyBoard/v1.0.0.zip (just v1.0.0.zip, not MyBoard.v1.0.0.zip)
After:
- Staging: .pcb/releases/MyBoard-v1.0.0/
- Zip: .pcb/releases/MyBoard-v1.0.0.zip
> Make `pcb tag` and `pcb release` consistent

- Cargo.lock
- Cargo.toml
updating the ruff version in Cargo.toml fixes the build errors in flake.nix
> update ruff v0.4.10 -> 0.13.0 to fix nix flake

- crates/pcb/src/build.rs
- crates/pcb/src/file_walker.rs
- crates/pcb/src/fmt.rs
- crates/pcb/src/layout.rs
- crates/pcb/src/main.rs
- crates/pcb/src/open.rs
- crates/pcb/src/test.rs
- crates/pcb/src/upgrade/mod.rs
By default:
```
/// - Always recursive traversal
/// - Always skips vendor/ directories  
/// - Always respects git ignore patterns
/// - Filters to .zen files only
```
> Standardize file walking in all pcb subcommands

- crates/pcb-zen-core/src/lib.rs
- crates/pcb/src/vendor.rs
LSP should never panic. Just propagate the error to the client. This should just be a transient state. Also, remove redundant file existence check.
> Fail gracefully when current file has no spec

- crates/pcb-sch/src/bom.rs
- crates/pcb-sch/src/lib.rs
- crates/pcb-zen-core/src/config.rs
- crates/pcb/src/bom.rs
- crates/pcb/src/release.rs
If there is no Zen BOM and there is a kicad_sch file, then try to parse BOM from the kicad_sch file instead and generate our standard-structure design BOM.
This also works with the `pcb bom` command.
Example releases:
- https://app.diode.computer/singularity/SN0001/releases/a772b2f7-b371-4ee6-86f9-7603f3f6db97/bom
- https://app.diode.computer/singularity/SN0002/releases/4e0647e2-c4be-42c6-9b4c-f5d1812655eb/bom
> Add support for kicad schematic bom as fallback

- crates/pcb-sch/src/lib.rs
Some test points may require parts.
> Don't auto DNP TP* designators

- crates/pcb-zen-core/src/lang/interface.rs
- crates/pcb-zen-core/tests/snapshots/interface__interface_comprehensive_net_promotion.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_transitive_promotion.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_using_chain_validation.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_using_promotion_serialization.snap
- crates/pcb-zen-core/tests/snapshots/interface__interface_using_serialization_roundtrip.snap
- crates/pcb-zen/tests/snapshots/interface_templates_snapshot__interface_using_promotion_targets.snap
Before: check that interface has 1 field and that it is a net
After: check that interface has 1 net field (and no interfaces)
This allows for adding metadata fields without changing the net naming.
This should (hopefully) not cause that much churn because we haven't
really used metadata fields in interfaces yet.
Signed-off-by: akhilles <akhilvelagapudi@gmail.com>
> Fix single-net interface net naming

- crates/pcb-zen-core/src/convert.rs
- crates/pcb-zen-core/src/lang/builtin.rs
- crates/pcb-zen-core/src/lang/electrical_check.rs
- crates/pcb-zen-core/src/lang/mod.rs
- crates/pcb-zen-core/src/lang/module.rs
- crates/pcb-zen-core/src/lang/physical.rs
- crates/pcb-zen/src/diagnostics.rs
- crates/pcb/src/build.rs
- crates/pcb/tests/electrical_checks.rs
- crates/pcb/tests/snapshots/build__deny_warnings_flag.snap
- crates/pcb/tests/snapshots/electrical_checks__error_severity.snap
- crates/pcb/tests/snapshots/electrical_checks__invalid_severity.snap
- crates/pcb/tests/snapshots/electrical_checks__passing_check.snap
- crates/pcb/tests/snapshots/electrical_checks__warning_severity.snap
- crates/pcb/tests/snapshots/electrical_checks__with_inputs.snap
- crates/pcb/tests/snapshots/path__path_local_mixed_release.snap
- docs/pages/spec.mdx
- examples/electrical_checks.zen
- examples/power_checks.zen
This is the precursor to erc checks with more syntactic sugar, but this is enough to do a lot in stdlib.
Check fns are evaluated lazily. There are provided the frozen module as well as the inputs. No fancy reporting like `pcb test`. We just raise warning/error diagnostics based on the results of the check fn. Severity can be set through an argument, so we can warning-only checks, or even ignore checks by dropping them to "advice" severity.
> Add `builtin.add_electrical_check`

- crates/pcb-zen/src/git.rs
The previous implementation only fetched the default refspec, which could
miss new tags, branches, or force-updated refs. This caused worktree
creation to fail when trying to check out newly published versions.
Now explicitly fetches:
- All tags (--tags)
- All branches (+refs/heads/*:refs/heads/*)
- Force-updated refs (--force)
- Prunes deleted refs (--prune, --prune-tags)
Signed-off-by: akhilles <akhilvelagapudi@gmail.com>
> Fetch all tags and branches when updating git dependencies

- crates/pcb-zen-core/tests/component.rs
- crates/pcb-zen-core/tests/snapshots/component__component_duplicate_pin_names.snap
Both component_duplicate_pin_names and
component_manufacturer_from_symbol were using test_symbol.kicad_sym,
which caused the contents of one test to be visible to the other. Use
different file names as a short-term fix for this.
Example CI flakes: https://github.com/diodeinc/pcb/actions/runs/18253545573/job/51971797596?pr=212
Signed-off-by: akhilles <akhilvelagapudi@gmail.com>
> Fix flaky test race condition

- crates/pcb-layout/src/scripts/update_layout_file.py
- crates/pcb-zen-core/src/convert.rs
- crates/pcb-zen-core/src/lang/component.rs
- crates/pcb-zen-core/src/lang/stackup.rs
- crates/pcb-zen-core/src/lib.rs
- docs/pages/spec.mdx
- examples/board_config.zen
Also, sets the built-in "Datasheet" field instead of adding a custom "datasheet" field.
> Add `spec` to `BoardConfg()` and `datasheet` to `Component()`

- crates/pcb-zen-core/src/lang/stackup.rs
- docs/pages/spec.mdx
- examples/board_config.zen
This is only for internal use as kicad only supports power.
> Add "ground" copper role, don't use role in symmetric checks
